version: '3'
services:
  jenkins:
    container_name: jenkins
    image: grambell003/jenkins:v2
    ports:
      - "80:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"